/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE allocateBase PLEASE EDIT ../allocate.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Faculty } from '../faculty';
import { Project } from '../project';
import { Student } from '../student';

/**
 * This is the model of allocate object
 *
 */
export class AllocateBase {

    constructor() { }

    public _id: string;
    public fname?: string;
    public pname?: string;
    public sname?: string;
    public validate?: Boolean;
    // Relations faculty
    public faculty: Faculty | string;
    // Relations project
    public project: Project | string;
    // Relations student
    public student: Student | string;
}
